apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raresum-com/platform.git
    targetRevision: main
    path: cluster/overlays/dev-local
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
