apiVersion: v1
kind: Service
metadata:
  name: supabase-gateway-nodeport
  namespace: supabase
spec:
  type: NodePort
  selector:
    app: supabase-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31380

