---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-nodeport
  namespace: tools
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
  ports:
    - name: minio-console
      port: 9001
      targetPort: 9001
      nodePort: 31302  # MinIO Console UI - use available port
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-nodeport
  namespace: tools
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
      nodePort: 31301  # MinIO S3 API - use available port
