apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    helm:
      releaseName: supabase
      values: |
        # PostgreSQL (dev: ephemeral)
        postgresql:
          auth:
            username: supabase_admin
            password: supabase_pass
            database: supabase
          primary:
            persistence:
              enabled: false
          volumePermissions:
            enabled: true

        # Enable only essentials for dev-local
        studio:
          enabled: true
          extraEnv:
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333
            - name: SUPABASE_URL
              value: http://supabase-supabase-rest:3000
            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: "none"
        rest:
          enabled: true
          extraEnv:
            - name: PGRST_DB_URI
              value: postgres://supabase_admin:supabase_pass@supabase-supabase-db.supabase.svc.cluster.local:5432/supabase
        auth:
          enabled: true
          extraEnv:
            - name: GOTRUE_JWT_SECRET
              value: dev-local-jwt-secret-change-me
            - name: GOTRUE_SITE_URL
              value: http://localhost:3333
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333
        storage:
          enabled: true
          externalS3:
            enabled: true
            endpoint: http://minio.tools.svc.cluster.local:9000
            accessKey: minioadmin
            secretKey: minioadmin123
            bucket: dev-local

        # Disable nonessential modules for dev-local
        realtime:
          enabled: false
        functions:
          enabled: false
        analytics:
          enabled: false
        vector:
          enabled: false
        meta:
          enabled: false
        kong:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
