apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    helm:
      releaseName: supabase
      values: |
        # Secrets: reference existing secrets we create in overlay
        secret:
          jwt:
            secretRef: supabase-jwt
            secretRefKey:
              anonKey: anonKey
              serviceKey: serviceRoleKey
              secret: jwtSecret
          db:
            secretRef: supabase-db
            secretRefKey:
              username: username
              password: password
              database: database

        # Database (dev: ephemeral) and tag pin
        db:
          enabled: true
          image:
            tag: "15.1.0.147"
          persistence:
            enabled: false
          environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

        # Studio
        studio:
          enabled: true
          image:
            tag: "20240326-5e5586d"
          environment:
            SUPABASE_PUBLIC_URL: http://localhost:3333
            SUPABASE_URL: http://supabase-supabase-rest:3000
            NEXT_PUBLIC_ENABLE_LOGS: "true"
            NEXT_ANALYTICS_BACKEND_PROVIDER: postgres

        # REST (PostgREST)
        rest:
          enabled: true
          image:
            tag: "v12.0.1"
          environment:
            PGRST_DB_SCHEMAS: public,storage,graphql_public
            PGRST_DB_ANON_ROLE: anon

        # Auth (GoTrue)
        auth:
          enabled: true
          image:
            tag: "v2.143.0"
          environment:
            API_EXTERNAL_URL: http://localhost:3333
            GOTRUE_SITE_URL: http://localhost:3333
            GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
            GOTRUE_MAILER_AUTOCONFIRM: "true"
            GOTRUE_SMTP_ADMIN_EMAIL: "dev@example.local"
            GOTRUE_SMTP_HOST: "localhost"
            GOTRUE_SMTP_PORT: "25"
            GOTRUE_SMTP_SENDER_NAME: "dev"

        # Storage -> external S3 (MinIO)
        storage:
          enabled: true
          image:
            tag: "v0.46.4"
          environment:
            STORAGE_BACKEND: s3
            GLOBAL_S3_ENDPOINT: http://minio.tools.svc.cluster.local:9000
            GLOBAL_S3_PROTOCOL: http
            GLOBAL_S3_FORCE_PATH_STYLE: true
            AWS_DEFAULT_REGION: dev
          persistence:
            enabled: false

        # Disable nonessential modules for dev-local
        realtime:
          enabled: false
        functions:
          enabled: false
        analytics:
          enabled: false
        vector:
          enabled: false
        meta:
          enabled: false
        kong:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
