apiVersion: v1
kind: Secret
metadata:
  name: supabase-db
  namespace: supabase
type: Opaque
stringData:
  username: supabase_admin
  password: supabase_pass
  database: supabase
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  namespace: supabase
type: Opaque
stringData:
  anonKey: dev-local-anon-key
  serviceRoleKey: dev-local-service-role-key
  jwtSecret: dev-local-jwt-secret-change-me

