apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-supabase-db-pvc
  namespace: supabase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path

