apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    helm:
      releaseName: supabase
      values: |
        # API Configuration
        api:
          external_url: http://localhost:31380

        # Secrets: reference existing secrets we create in overlay
        secret:
          jwt:
            secretRef: supabase-jwt
            secretRefKey:
              anonKey: anonKey
              serviceKey: serviceRoleKey
              secret: secret
          db:
            secretRef: supabase-db
            secretRefKey:
              username: username
              password: password
              database: database
          s3:
            secretRef: supabase-s3
            secretRefKey:
              keyId: keyId
              accessKey: accessKey

        # Database (enabled persistence for dev-local) and tag pin
        db:
          enabled: true
          image:
            tag: "15.1.0.147"
          persistence:
            enabled: true
            size: 20Gi
            storageClass: local-path
            accessModes:
              - ReadWriteOnce
          environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

        # Studio
        studio:
          enabled: true
          image:
            tag: "20240326-5e5586d"
          environment:
            # Override default URLs that point to example.com
            SUPABASE_PUBLIC_URL: http://localhost:31380
            SUPABASE_URL: http://supabase-gateway
            STUDIO_PG_META_URL: http://localhost:31380/pg-meta
            NEXT_PUBLIC_SUPABASE_URL: http://localhost:31380
            NEXT_PUBLIC_ENABLE_LOGS: "true"
            NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
          extraEnv:
            - name: HOST
              value: 0.0.0.0
            - name: HOSTNAME
              value: 0.0.0.0
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt
                  key: anonKey

        # REST (PostgREST)
        rest:
          enabled: true
          image:
            tag: "v12.0.1"
          environment:
            PGRST_DB_SCHEMAS: public,storage,graphql_public
            PGRST_DB_ANON_ROLE: anon

        # Auth (GoTrue)
        auth:
          enabled: true
          image:
            tag: "v2.143.0"
          environment:
            GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
            API_EXTERNAL_URL: http://localhost:3333
            GOTRUE_SITE_URL: http://localhost:3333
            GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
            GOTRUE_MAILER_AUTOCONFIRM: "true"
            GOTRUE_SMTP_ADMIN_EMAIL: "dev@example.local"
            GOTRUE_SMTP_HOST: "localhost"
            GOTRUE_SMTP_PORT: "25"
            GOTRUE_SMTP_SENDER_NAME: "dev"

        # Storage -> external S3 (MinIO)
        storage:
          enabled: true
          image:
            tag: "v0.46.4"
          environment:
            STORAGE_BACKEND: s3
            # S3 Configuration
            GLOBAL_S3_ENDPOINT: http://minio.tools.svc.cluster.local:9000
            GLOBAL_S3_PROTOCOL: http
            GLOBAL_S3_FORCE_PATH_STYLE: "true"
            GLOBAL_S3_BUCKET: dev-local
            REGION: us-east-1
            AWS_DEFAULT_REGION: us-east-1
            # Required environment variables for storage service
            POSTGREST_URL: http://supabase-supabase-rest:3000
            PGOPTIONS: "-c search_path=storage,public"
            DATABASE_URL: postgres://postgres:supabase_pass@supabase-supabase-db:5432/postgres
            FILE_SIZE_LIMIT: "52428800"
            TENANT_ID: stub
            PROJECT_REF: stub
            # JWT Configuration for storage service
            JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
            PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
            # Enable storage features  
            STORAGE_S3_REGION: us-east-1
            STORAGE_S3_ENDPOINT: http://minio.tools.svc.cluster.local:9000
            STORAGE_S3_FORCE_PATH_STYLE: "true"
          persistence:
            enabled: false

        # Disable nonessential modules for dev-local
        realtime:
          enabled: false
        functions:
          enabled: false
        analytics:
          enabled: false
        vector:
          enabled: false
        meta:
          enabled: true
          image:
            tag: "v0.80.0"
        kong:
          enabled: false  # Disabled - using custom gateway instead
      parameters:
        - name: db.image.tag
          value: "15.1.0.147"
        - name: studio.image.tag
          value: "20240326-5e5586d"
        - name: rest.image.tag
          value: "v12.0.1"
        - name: auth.image.tag
          value: "v2.143.0"
        - name: storage.image.tag
          value: "v0.46.4"
        - name: realtime.enabled
          value: "false"
        - name: functions.enabled
          value: "false"
        - name: analytics.enabled
          value: "false"
        - name: vector.enabled
          value: "false"
        - name: meta.enabled
          value: "true"
        - name: kong.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
