apiVersion: v1
kind: Secret
metadata:
  name: supabase-db
  namespace: supabase
type: Opaque
stringData:
  username: postgres
  password: supabase_pass
  password_encoded: supabase_pass
  database: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  namespace: supabase
type: Opaque
stringData:
  anonKey: dev-local-anon-key
  serviceRoleKey: dev-local-service-role-key
  secret: dev-local-jwt-secret-change-me
