apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 14.7.16
    helm:
      releaseName: minio
      values: |
        mode: standalone
        resources:
          requests: { cpu: 100m, memory: 256Mi }
        persistence:
          size: 5Gi
        auth:
          rootUser: "minioadmin"
          rootPassword: "minioadmin123"   # sadece lokal için
        defaultBuckets: "dev-local"
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
