apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    helm:
      releaseName: supabase
      values: |
        # --- PostgreSQL (dev için kalıcılık kapalı) ---
        postgresql:
          auth:
            username: supabase_admin
            password: supabase_pass
            database: supabase
          primary:
            persistence:
              enabled: false
          volumePermissions:
            enabled: true

        # --- Sadece gerekli modüller açık ---
        studio:
          enabled: true
          extraEnv:
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333
            - name: SUPABASE_URL
              value: http://supabase-supabase-rest:3000
            - name: STUDIO_PG_META_URL
              value: ""
            - name: LOGFLARE_URL
              value: ""
            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: "none"
        rest:
          enabled: true
        auth:
          enabled: true
        storage:
          enabled: true

        # Geri kalan her şey kapalı
        realtime: { enabled: false }
        functions: { enabled: false }
        analytics: { enabled: false }
        vector: { enabled: false }
        meta: { enabled: false }
        kong: { enabled: false }

        # --- REST (PostgREST) DB bağlantısı ---
        rest:
          enabled: true
          extraEnv:
            - name: PGRST_DB_URI
              value: postgres://supabase_admin:supabase_pass@supabase-supabase-db.supabase.svc.cluster.local:5432/supabase

        # --- Auth (GoTrue) minimum env ---
        auth:
          enabled: true
          image:
            repository: supabase/gotrue
            tag: v2.165.1
          extraEnv:
            - name: GOTRUE_JWT_SECRET
              value: dev-local-jwt-secret-change-me
            - name: GOTRUE_SITE_URL
              value: http://localhost:3333
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333

        # --- Storage → MinIO ---
        storage:
          enabled: true
          externalS3:
            enabled: true
            endpoint: http://minio.tools.svc.cluster.local:9000
            accessKey: minioadmin
            secretKey: minioadmin123
            bucket: dev-local

        # --- Global: pull secret (rate limit'e karşı) ---
        global:
          env:
            - name: JWT_SECRET
              value: dev-local-jwt-secret-change-me
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333
          imagePullSecrets:
            - name: dockerhub-creds
  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
