apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/supabase-community/supabase-kubernetes.git
    targetRevision: main
    path: charts/supabase
    helm:
      releaseName: supabase
      values: |
        # --- PostgreSQL (lokal geliştirme: kalıcılık KAPALI) ---
        postgresql:
          auth:
            username: supabase_admin
            password: supabase_pass
            database: supabase
          primary:
            persistence:
              enabled: false
          volumePermissions:
            enabled: true

        # --- Studio ---
        studio:
          enabled: true

        # --- REST (PostgREST) ---
        rest:
          enabled: true
          extraEnv:
            - name: PGRST_DB_URI
              value: postgres://supabase_admin:supabase_pass@supabase-supabase-db.supabase.svc.cluster.local:5432/supabase

        # --- Auth (GoTrue) ---
        auth:
          enabled: true
          extraEnv:
            - name: GOTRUE_JWT_SECRET
              value: dev-local-jwt-secret-change-me
            - name: GOTRUE_SITE_URL
              value: http://localhost:3333
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333

        # --- Storage → MinIO ---
        storage:
          enabled: true
          externalS3:
            enabled: true
            endpoint: http://minio.tools.svc.cluster.local:9000
            accessKey: minioadmin
            secretKey: minioadmin123
            bucket: dev-local

        # --- Şimdilik kapalı modüller (lokal için sade kurulum) ---
        realtime:
          enabled: false
        functions:
          enabled: false
        analytics:
          enabled: false
        vector:
          enabled: false
        meta:
          enabled: false
        kong:
          enabled: false

        # --- Global env (bazı bileşenler ortak kullanır) ---
        global:
          env:
            - name: JWT_SECRET
              value: dev-local-jwt-secret-change-me
            - name: SUPABASE_PUBLIC_URL
              value: http://localhost:3333
          imagePullSecrets:
            - name: dockerhub-creds

  destination:
    server: https://kubernetes.default.svc
    namespace: supabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
